### ISSUE TITLE
"Allow location access" prompt

### ISSUE THREAD

**Issue by dazz397** [shipperhq/module-address-autocomplete#9] opened 2017-11-30 00:26 UTC
Whenever the autocomplete loads the browser pops a warning that the website wants to access your location. Is is possible to disable this since you do not need to know the users location to help fill out an address?

**Comment by wsaanthony** [comment] 2017-12-22 20:47
Hello,

Thanks for reaching out to us for this. I've tested this using a clean M2 instance and autocomplete installed but I wasn't able to see that warning you're referring to and it doesn't sound like native functionality for that extension

This means many other people aren't experiencing this behavior so I would try to approach this as a setting that's getting called by your browser or somewhere outside of autocomplete. Also if you use any other 3rd party extensions it might be worth disabling them and retesting to find the root cause here.

**Comment by wsaDemo** [comment] 2017-12-22 20:48
-- Please reply above this line --


Hello, 

Thanks for contacting ShipperHQ.

The ShipperHQ team will be out of the office for Christmas Day on
December 25th and New Year on January 1st. Between December 26th and
29th we will be providing limited support for urgent issues.

We will be monitoring this email address for any critical issues
during this period.

For non-urgent enquiries, we look forward to working with you once on
our return on Tuesday, January 2nd.

Wishing you all a very merry Christmas and happy New Year from the
ShipperHQ team!

**Comment by dazz397** [comment] 2017-12-22 21:53
I have attached a screenshot of it in both firefox and chrome.  It does not happen until you start typing into the street address field.  If you allow location access once it will not prompt again.
![chrome](https://user-images.githubusercontent.com/25210111/34313289-e9711186-e71e-11e7-917e-6d92a435c853.jpg)
![firefox](https://user-images.githubusercontent.com/25210111/34313290-e988ccd6-e71e-11e7-931a-0952de6f3187.jpg)

Also I noticed the instructions here are ambiguous
http://docs.shipperhq.com/setting-up-google-maps-api-keys/

It says you need 
Google Places API Web Service
Google Maps Geocoding API
then in mentions you need "Google Places API Web Service" again at the bottom

But I also had to add "Google Maps JavaScript API" to get it to work. Can you confirm these are the three things needed and the documentation is incorrect?

I am wondering if I enabled something that caused this so please confirm.

**Comment by wsaDemo** [comment] 2017-12-26 15:47
-- Please reply above this line --


Geolocation is used to give context to the autocomplete. For example
if I, here in Dallas, type "1000 Main St" my top results for
autocomplete will be different than those someone in, say San
Francisco sees. If the geolocation permission is denied then the API
will just do it's best with the information it does have.

Is there a particular use case for disabling the geolocation prompt?

And thanks for pointing out the docs issue, the Javascript API is the
third API needed, you are correct.

 Regards, 

 Travis 
   [1]   SHIPPERHQ  | support@shipperhq.com [2]
US +1 (512) 215-4282 | UK +44 (0)1722-446240
 [3]  [4]

How would you rate my reply?
Great [5]    Okay [6]    Not Good [7]


Links:
------
[1] http://www.ShipperHQ.com
[2] mailto:support@shipperhq.com
[3] http://www.twitter.com/shipperhq
[4] http://www.facebook.com/shipperhq
[5]
https://secure.helpscout.net/satisfaction/158591904/record/1338941846/1/
[6]
https://secure.helpscout.net/satisfaction/158591904/record/1338941846/2/
[7]
https://secure.helpscout.net/satisfaction/158591904/record/1338941846/3/

**Comment by dazz397** [comment] 2017-12-27 21:08
Well, many people have issues with trusting small ecommerce sites. When they check out and a pop up comes up saying the site wants access to their location without a specific reason it may cause them to back out. Most users will not relate that the website has auto complete enabled on the billing address field and that's why it wants access to their location.

**Comment by wsakaren** [comment] 2017-12-27 21:24
Thanks for explanation, appreciate your input.

So there are 2 scenarios here:

1. Ask for location access and give more accurate results
2. Not have location access and just go off what the customer enters

Different merchants will want to do different things, I agree with your scenario, we are raising a feature enhancement JIRA to make location access an optional request. Will let you know here once its in (will be in next 2-3 weeks, probably sooner).

**Comment by TravisBernard** [comment] 2018-05-09 14:26
Hey @dazz397 thanks for bringing this up and for your patience while we rolled it out. This feature was released this morning (v20.2.0). There is a new setting in Configuration > Sales > Shipping Settings > ShipperHQ Address Autocomplete called Use Geolocation. By turning the setting off (on by default) you can disable the geolocation request. This trades out autocomplete accuracy/speed for the benefit of not having a location access prompt.

**Closed** 2018-05-09 14:27 UTC
